export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'
export const USER_FETCH_RESET = 'USER_FETCH_RESET'

export const USER_ADD_REQUEST = 'USER_ADD_REQUEST'
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS'
export const USER_ADD_FAIL = 'USER_ADD_FAIL'
export const USER_ADD_RESET = 'USER_ADD_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const SELLER_FETCH_REQUEST = 'SELLER_FETCH_REQUEST'
export const SELLER_FETCH_SUCCESS = 'SELLER_FETCH_SUCCESS'
export const SELLER_FETCH_FAIL = 'SELLER_FETCH_FAIL'
export const SELLER_FETCH_RESET = 'SELLER_FETCH_RESET'

export const SELLER_ADD_REQUEST = 'SELLER_ADD_REQUEST'
export const SELLER_ADD_SUCCESS = 'SELLER_ADD_SUCCESS'
export const SELLER_ADD_FAIL = 'SELLER_ADD_FAIL'
export const SELLER_ADD_RESET = 'SELLER_ADD_RESET'

export const CATEGORY_FETCH_REQUEST = 'CATEGORY_FETCH_REQUEST'
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS'
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL'
export const CATEGORY_FETCH_RESET = 'CATEGORY_FETCH_RESET'

export const CATEGORY_ADD_REQUEST = 'CATEGORY_ADD_REQUEST'
export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS'
export const CATEGORY_ADD_FAIL = 'CATEGORY_ADD_FAIL'
export const CATEGORY_ADD_RESET = 'CATEGORY_ADD_RESET'

export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'
export const PRODUCT_FETCH_RESET = 'PRODUCT_FETCH_RESET'
