export const ADDRESS_FETCH_REQUEST = 'ADDRESS_FETCH_REQUEST'
export const ADDRESS_FETCH_SUCCESS = 'ADDRESS_FETCH_SUCCESS'
export const ADDRESS_FETCH_FAIL = 'ADDRESS_FETCH_FAIL'
export const ADDRESS_FETCH_RESET = 'ADDRESS_FETCH_RESET'

export const ADDRESS_ADD_REQUEST = 'ADDRESS_ADD_REQUEST'
export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS'
export const ADDRESS_ADD_FAIL = 'ADDRESS_ADD_FAIL'
export const ADDRESS_ADD_RESET = 'ADDRESS_ADD_RESET'

export const BANK_FETCH_REQUEST = 'BANK_FETCH_REQUEST'
export const BANK_FETCH_SUCCESS = 'BANK_FETCH_SUCCESS'
export const BANK_FETCH_FAIL = 'BANK_FETCH_FAIL'
export const BANK_FETCH_RESET = 'BANK_FETCH_RESET'

export const BANK_ADD_REQUEST = 'BANK_ADD_REQUEST'
export const BANK_ADD_SUCCESS = 'BANK_ADD_SUCCESS'
export const BANK_ADD_FAIL = 'BANK_ADD_FAIL'
export const BANK_ADD_RESET = 'BANK_ADD_RESET'

export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'
export const PRODUCT_FETCH_RESET = 'PRODUCT_FETCH_RESET'

export const CARTITEMLIST_FETCH_REQUEST = 'CARTLIST_FETCH_REQUEST'
export const CARTITEMLIST_FETCH_SUCCESS = 'CARTLIST_FETCH_SUCCESS'
export const CARTITEMLIST_FETCH_FAIL = 'CARTLIST_FETCH_FAIL'
export const CARTITEMLIST_FETCH_RESET = 'CARTLIST_FETCH_RESET'

// export const BANK_ADD_REQUEST = 'ADD_TO_CART_REQUEST'
// export const BANK_ADD_SUCCESS = 'ADD_TO_CART_SUCCESS'
// export const BANK_ADD_FAIL = 'ADD_TO_CART_FAIL'
// export const BANK_ADD_RESET = 'ADD_TO_CART_RESET'

export const ORDER_FETCH_REQUEST = 'ORDER_FETCH_REQUEST'
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS'
export const ORDER_FETCH_FAIL = 'ORDER_FETCH_FAIL'
export const ORDER_FETCH_RESET = 'ORDER_FETCH_RESET'
