export const ORDERLIST_FETCH_REQUEST = 'ORDERLIST_FETCH_REQUEST'
export const ORDERLIST_FETCH_SUCCESS = 'ORDERLIST_FETCH_SUCCESS'
export const ORDERLIST_FETCH_FAIL = 'ORDERLIST_FETCH_FAIL'
export const ORDERLIST_FETCH_RESET = 'ORDERLIST_FETCH_RESET'
